# Generated by Django 5.0.6 on 2024-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazenamento',
            name='tipo_armazenamento',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='marca',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='unidade_medida',
            name='unidade_medida',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
